Implement MeshCNN
NVIDIAGameWorks/kaolin pull request #205
Opened 2020-04-21 22:11 UTC by krrish94

* Implement MeshCNN in Kaolin
* Also port a fix for adjacency-info from @Caenorst 

Signed-off-by: Krishna Murthy <krrish94@gmail.com>

2020-04-27 16:34 UTC, Caenorst requested changes
Pre-review.

On kaolin/models/meshcnn.py:
We need to have documentation on all the functions (especially for the arguments).
We need to have unit tests for all those functions.
I know is currently not enforced but please avoid using raw string in documentation if you don't need it.

2020-04-27 16:34 UTC, Caenorst commented on kaolin/models/meshcnn.py
> +def compute_face_normals_for_mesh(mesh):
This function have a very similar name than https://github.com/NVIDIAGameWorks/kaolin/blob/83002fedc67e1c9112a8f834ffb4f8a890e6042a/kaolin/rep/TriangleMesh.py#L154 but a different computation (can you explain ?)

2020-04-27 16:34 UTC, Caenorst commented on kaolin/models/meshcnn.py
> +    face_normals = face_normals / face_normal_lengths[..., None]
`unqueeze(-1)` at line 61 and `[..., None]` here ?

2020-04-27 16:34 UTC, Caenorst commented on tests/examples/run/test_classification.sh
> +python ${KAOLIN_HOME}/examples/Classification/mesh_classification.py \
In tests the CI catch the returned value of the script, if you run those two commands like that if the first command fails the return value is gonna be overriden by this one.

I recommend using command1 && command2

2020-04-27 16:54 UTC, krrish94 commented on kaolin/models/meshcnn.py
> +def compute_face_normals_for_mesh(mesh):
As the comment in `compute_face_normals` in `rep/TriangleMesh.py` says, we have a "more robust" normal computation scheme, where we average normals for each vertex to compute the face normal.

Here, I've chosen this computation (as opposed to Kaolin's impl) to exactly align with the feature computation scheme employed in MeshCNN.

2020-04-27 16:56 UTC, krrish94 commented
Also, for the docstrings, I currently added docstrings only for functions that are exposed externally. All other functions are used only within this file.

Still, I think it's reasonable to add docstrings and unittests for all modules regardless. Will do

2020-04-28 17:27 UTC, Caenorst approved these changes
LGTM !

2020-04-28 17:27 UTC, merged