Fix #453, return_sparse for trianglemeshes_to_voxelgrids
NVIDIAGameWorks/kaolin pull request #455
Opened 2021-10-17 14:16 UTC by Talmaj

- Add test for return_sparse=True for trianglemeshes_to_voxelgrids
- Fix return_sparse=True for trianglemeshes_to_voxelgrids

This solution might be a bit less memory efficient, because of the use of `torch.cat`, but as far as I know, one cannot do `voxelgrids[i] = voxelgrid` with sparse tensors.

2021-10-18 17:46 UTC, Caenorst requested changes
Good catch! Thank you for addressing your contribution, I just have a tiny comment over the parametrization of the test, otherwise LGTM.

2021-10-18 17:46 UTC, Caenorst commented on tests/python/kaolin/ops/conversions/test_trianglemesh.py
> +)
You can chain pytest.mark.parametrize decorator like so:
```
@pytest.mark.parametrize('device', FLOAT_TYPES)
@pytest.mark.parametrize('return_sparse', [True, False])
class TestTriangleMeshToVoxelgrid
```

2021-10-19 14:37 UTC, Talmaj commented on tests/python/kaolin/ops/conversions/test_trianglemesh.py
> +)
Good advice, I forgot that's possible. I've fixed it.

2021-10-19 14:41 UTC, Caenorst commented
From our guideline all the commits must be signed, you can follow the suggestion from https://github.com/NVIDIAGameWorks/kaolin/pull/455/checks?check_run_id=3940587719 to fix the DCO check

You can ignore the CI tests, the CI runner have some issue.

2021-10-20 01:49 UTC, Caenorst approved these changes
LGTM! Thank you for your contribution!

2021-10-20 01:49 UTC, merged